openapi: 3.2.0
info:
  version: 2020-07-20
  x-release: v4
  title: 'AWS Proton #X Amz Target=AwsProton20200720.CreateTemplateSyn…'
  description: This is the Proton Service API Reference.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: proton
  x-aws-signingName: proton
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/proton-2020-07-20.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://proton.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Proton multi-region endpoint
- url: https://proton.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Proton multi-region endpoint
- url: http://proton.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Proton endpoint for China (Beijing) and China (Ningxia)
- url: https://proton.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Proton endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AwsProton20200720.CreateTemplateSyncConfig'
paths:
  /#X-Amz-Target=AwsProton20200720.CreateTemplateSyncConfig:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: CreateTemplateSyncConfig
      description: 'Set up a template to create new template versions automatically by tracking a linked repository. A linked repository is a repository that has been registered with Proton. For more information, see CreateRepository.


        When a commit is pushed to your linked repository, Proton checks for changes to your repository template bundles. If it detects a template bundle change, a new major or minor version of its template is created, if the version doesn’t already exist. For more information, see Template sync configurations in the Proton User Guide.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTemplateSyncConfigOutput'
        '480':
          description: ServiceQuotaExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceQuotaExceededException'
        '481':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '482':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '483':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '484':
          description: ConflictException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
        '485':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTemplateSyncConfigInput'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AwsProton20200720.CreateTemplateSyncConfig
      summary: Amazon Proton Create Template Sync Config
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AwsProton20200720.CreateTemplateSyncConfig'
components:
  schemas:
    Subdirectory:
      type: string
      minLength: 1
      maxLength: 4096
    ResourceName:
      type: string
      pattern: ^[0-9A-Za-z]+[0-9A-Za-z_\-]*$
      minLength: 1
      maxLength: 100
    ValidationException: {}
    RepositoryName:
      type: string
      pattern: '[A-Za-z0-9_.-].*/[A-Za-z0-9_.-].*'
      minLength: 1
      maxLength: 100
    CreateTemplateSyncConfigOutput:
      type: object
      properties:
        templateSyncConfig:
          allOf:
          - $ref: '#/components/schemas/TemplateSyncConfig'
          - description: The template sync configuration detail data that's returned by Proton.
    RepositoryProvider:
      type: string
      enum:
      - GITHUB
      - GITHUB_ENTERPRISE
      - BITBUCKET
    CreateTemplateSyncConfigInput:
      type: object
      required:
      - branch
      - repositoryName
      - repositoryProvider
      - templateName
      - templateType
      title: CreateTemplateSyncConfigInput
      properties:
        branch:
          allOf:
          - $ref: '#/components/schemas/GitBranchName'
          - description: The repository branch for your template.
        repositoryName:
          allOf:
          - $ref: '#/components/schemas/RepositoryName'
          - description: The repository name (for example, <code>myrepos/myrepo</code>).
        repositoryProvider:
          allOf:
          - $ref: '#/components/schemas/RepositoryProvider'
          - description: The provider type for your repository.
        subdirectory:
          allOf:
          - $ref: '#/components/schemas/Subdirectory'
          - description: A repository subdirectory path to your template bundle directory. When included, Proton limits the template bundle search to this repository directory.
        templateName:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The name of your registered template.
        templateType:
          allOf:
          - $ref: '#/components/schemas/TemplateType'
          - description: The type of the registered template.
    ConflictException: {}
    ThrottlingException: {}
    ServiceQuotaExceededException: {}
    TemplateType:
      type: string
      enum:
      - ENVIRONMENT
      - SERVICE
    TemplateSyncConfig:
      type: object
      required:
      - branch
      - repositoryName
      - repositoryProvider
      - templateName
      - templateType
      properties:
        branch:
          allOf:
          - $ref: '#/components/schemas/GitBranchName'
          - description: The repository branch.
        repositoryName:
          allOf:
          - $ref: '#/components/schemas/RepositoryName'
          - description: The repository name (for example, <code>myrepos/myrepo</code>).
        repositoryProvider:
          allOf:
          - $ref: '#/components/schemas/RepositoryProvider'
          - description: The repository provider.
        subdirectory:
          allOf:
          - $ref: '#/components/schemas/Subdirectory'
          - description: A subdirectory path to your template bundle version.
        templateName:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The template name.
        templateType:
          allOf:
          - $ref: '#/components/schemas/TemplateType'
          - description: The template type.
      description: The detail data for a template sync configuration.
    AccessDeniedException: {}
    GitBranchName:
      type: string
      minLength: 1
      maxLength: 200
    InternalServerException: {}
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/proton/
x-hasEquivalentPaths: true
