openapi: 3.2.0
info:
  version: 2020-07-20
  x-release: v4
  title: 'AWS Proton #X Amz Target=AwsProton20200720.ListEnvironmentAc…'
  description: This is the Proton Service API Reference.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: proton
  x-aws-signingName: proton
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/proton-2020-07-20.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://proton.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Proton multi-region endpoint
- url: https://proton.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Proton multi-region endpoint
- url: http://proton.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Proton endpoint for China (Beijing) and China (Ningxia)
- url: https://proton.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Proton endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AwsProton20200720.ListEnvironmentAccountConnections'
paths:
  /#X-Amz-Target=AwsProton20200720.ListEnvironmentAccountConnections:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListEnvironmentAccountConnections
      description: 'View a list of environment account connections.


        For more information, see Environment account connections in the Proton User guide.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListEnvironmentAccountConnectionsOutput'
        '480':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '481':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '482':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '483':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListEnvironmentAccountConnectionsInput'
      parameters:
      - name: maxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AwsProton20200720.ListEnvironmentAccountConnections
      summary: Amazon Proton List Environment Account Connections
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AwsProton20200720.ListEnvironmentAccountConnections'
components:
  schemas:
    EnvironmentAccountConnectionStatus:
      type: string
      enum:
      - PENDING
      - CONNECTED
      - REJECTED
    ResourceName:
      type: string
      pattern: ^[0-9A-Za-z]+[0-9A-Za-z_\-]*$
      minLength: 1
      maxLength: 100
    EnvironmentAccountConnectionSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/EnvironmentAccountConnectionSummary'
    ValidationException: {}
    EnvironmentAccountConnectionRequesterAccountType:
      type: string
      enum:
      - MANAGEMENT_ACCOUNT
      - ENVIRONMENT_ACCOUNT
    ListEnvironmentAccountConnectionsOutput:
      type: object
      required:
      - environmentAccountConnections
      properties:
        environmentAccountConnections:
          allOf:
          - $ref: '#/components/schemas/EnvironmentAccountConnectionSummaryList'
          - description: 'An array of environment account connections with details that''s returned by Proton. '
        nextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: A token that indicates the location of the next environment account connection in the array of environment account connections, after the current requested list of environment account connections.
    EnvironmentAccountConnectionId:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
    NextToken:
      type: string
      pattern: ^[A-Za-z0-9+=/]+$
    ListEnvironmentAccountConnectionsInput:
      type: object
      required:
      - requestedBy
      title: ListEnvironmentAccountConnectionsInput
      properties:
        environmentName:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The environment name that's associated with each listed environment account connection.
        maxResults:
          allOf:
          - $ref: '#/components/schemas/MaxPageResults'
          - description: The maximum number of environment account connections to list.
        nextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: A token that indicates the location of the next environment account connection in the array of environment account connections, after the list of environment account connections that was previously requested.
        requestedBy:
          allOf:
          - $ref: '#/components/schemas/EnvironmentAccountConnectionRequesterAccountType'
          - description: The type of account making the <code>ListEnvironmentAccountConnections</code> request.
        statuses:
          allOf:
          - $ref: '#/components/schemas/EnvironmentAccountConnectionStatusList'
          - description: The status details for each listed environment account connection.
    Arn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-us-gov):[a-zA-Z0-9-]+:[a-zA-Z0-9-]*:\d{12}:([\w+=,.@-]+[/:])*[\w+=,.@-]+$
      minLength: 1
      maxLength: 200
    EnvironmentAccountConnectionStatusList:
      type: array
      items:
        $ref: '#/components/schemas/EnvironmentAccountConnectionStatus'
    ThrottlingException: {}
    EnvironmentAccountConnectionArn:
      type: string
    Timestamp:
      type: string
      format: date-time
    MaxPageResults:
      type: integer
      minimum: 1
      maximum: 100
    InternalServerException: {}
    AwsAccountId:
      type: string
      pattern: ^\d{12}$
    AccessDeniedException: {}
    EnvironmentAccountConnectionSummary:
      type: object
      required:
      - arn
      - environmentAccountId
      - environmentName
      - id
      - lastModifiedAt
      - managementAccountId
      - requestedAt
      - roleArn
      - status
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/EnvironmentAccountConnectionArn'
          - description: The Amazon Resource Name (ARN) of the environment account connection.
        componentRoleArn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: <p>The Amazon Resource Name (ARN) of the IAM service role that Proton uses when provisioning directly defined components in the associated environment account. It determines the scope of infrastructure that a component can provision in the account.</p> <p>The environment account connection must have a <code>componentRoleArn</code> to allow directly defined components to be associated with any environments running in the account.</p> <p>For more information about components, see <a href="https://docs.aws.amazon.com/proton/latest/userguide/ag-components.html">Proton components</a> in the <i>Proton User Guide</i>.</p>
        environmentAccountId:
          allOf:
          - $ref: '#/components/schemas/AwsAccountId'
          - description: The ID of the environment account that's connected to the environment account connection.
        environmentName:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The name of the environment that's associated with the environment account connection.
        id:
          allOf:
          - $ref: '#/components/schemas/EnvironmentAccountConnectionId'
          - description: The ID of the environment account connection.
        lastModifiedAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time when the environment account connection was last modified.
        managementAccountId:
          allOf:
          - $ref: '#/components/schemas/AwsAccountId'
          - description: The ID of the management account that's connected to the environment account connection.
        requestedAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time when the environment account connection request was made.
        roleArn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The IAM service role that's associated with the environment account connection.
        status:
          allOf:
          - $ref: '#/components/schemas/EnvironmentAccountConnectionStatus'
          - description: The status of the environment account connection.
      description: Summary data of an Proton environment account connection resource.
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/proton/
x-hasEquivalentPaths: true
