openapi: 3.2.0
info:
  version: 2020-07-20
  x-release: v4
  title: 'AWS Proton #X Amz Target=AwsProton20200720.GetServiceTemplat…'
  description: This is the Proton Service API Reference.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: proton
  x-aws-signingName: proton
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/proton-2020-07-20.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://proton.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Proton multi-region endpoint
- url: https://proton.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Proton multi-region endpoint
- url: http://proton.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Proton endpoint for China (Beijing) and China (Ningxia)
- url: https://proton.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Proton endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AwsProton20200720.GetServiceTemplateVersion'
paths:
  /#X-Amz-Target=AwsProton20200720.GetServiceTemplateVersion:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: GetServiceTemplateVersion
      description: Get detailed data for a major or minor version of a service template.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetServiceTemplateVersionOutput'
        '480':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '481':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '482':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '483':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '484':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetServiceTemplateVersionInput'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AwsProton20200720.GetServiceTemplateVersion
      summary: Amazon Proton Get Service Template Version
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AwsProton20200720.GetServiceTemplateVersion'
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  schemas:
    ResourceName:
      type: string
      pattern: ^[0-9A-Za-z]+[0-9A-Za-z_\-]*$
      minLength: 1
      maxLength: 100
    ServiceTemplateSupportedComponentSourceType:
      type: string
      enum:
      - DIRECTLY_DEFINED
    ValidationException: {}
    CompatibleEnvironmentTemplateList:
      type: array
      items:
        $ref: '#/components/schemas/CompatibleEnvironmentTemplate'
    GetServiceTemplateVersionOutput:
      type: object
      required:
      - serviceTemplateVersion
      properties:
        serviceTemplateVersion:
          allOf:
          - $ref: '#/components/schemas/ServiceTemplateVersion'
          - description: The detailed data of the requested service template version.
    ResourceNotFoundException: {}
    TemplateVersionPart:
      type: string
      pattern: ^(0|([1-9]{1}\d*))$
      minLength: 1
      maxLength: 20
    GetServiceTemplateVersionInput:
      type: object
      required:
      - majorVersion
      - minorVersion
      - templateName
      title: GetServiceTemplateVersionInput
      properties:
        majorVersion:
          allOf:
          - $ref: '#/components/schemas/TemplateVersionPart'
          - description: To get service template major version detail data, include <code>major Version</code>.
        minorVersion:
          allOf:
          - $ref: '#/components/schemas/TemplateVersionPart'
          - description: To get service template minor version detail data, include <code>minorVersion</code>.
        templateName:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The name of the service template a version of which you want to get detailed data for.
    ServiceTemplateSupportedComponentSourceInputList:
      type: array
      items:
        $ref: '#/components/schemas/ServiceTemplateSupportedComponentSourceType'
    ThrottlingException: {}
    StatusMessage:
      type: string
      format: password
    TemplateSchema:
      type: string
      minLength: 1
      maxLength: 51200
      format: password
    ServiceTemplateVersion:
      type: object
      required:
      - arn
      - compatibleEnvironmentTemplates
      - createdAt
      - lastModifiedAt
      - majorVersion
      - minorVersion
      - status
      - templateName
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/ServiceTemplateVersionArn'
          - description: The Amazon Resource Name (ARN) of the version of a service template.
        compatibleEnvironmentTemplates:
          allOf:
          - $ref: '#/components/schemas/CompatibleEnvironmentTemplateList'
          - description: An array of compatible environment template names for the major version of a service template.
        createdAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time when the version of a service template was created.
        description:
          allOf:
          - $ref: '#/components/schemas/Description'
          - description: A description of the version of a service template.
        lastModifiedAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time when the version of a service template was last modified.
        majorVersion:
          allOf:
          - $ref: '#/components/schemas/TemplateVersionPart'
          - description: The latest major version that's associated with the version of a service template.
        minorVersion:
          allOf:
          - $ref: '#/components/schemas/TemplateVersionPart'
          - description: The minor version of a service template.
        recommendedMinorVersion:
          allOf:
          - $ref: '#/components/schemas/TemplateVersionPart'
          - description: The recommended minor version of the service template.
        schema:
          allOf:
          - $ref: '#/components/schemas/TemplateSchema'
          - description: The schema of the version of a service template.
        status:
          allOf:
          - $ref: '#/components/schemas/TemplateVersionStatus'
          - description: The service template version status.
        statusMessage:
          allOf:
          - $ref: '#/components/schemas/StatusMessage'
          - description: A service template version status message.
        supportedComponentSources:
          allOf:
          - $ref: '#/components/schemas/ServiceTemplateSupportedComponentSourceInputList'
          - description: <p>An array of supported component sources. Components with supported sources can be attached to service instances based on this service template version.</p> <p>For more information about components, see <a href="https://docs.aws.amazon.com/proton/latest/userguide/ag-components.html">Proton components</a> in the <i>Proton User Guide</i>.</p>
        templateName:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The name of the version of a service template.
      description: Detailed data of an Proton service template version resource.
    Description:
      type: string
      minLength: 0
      maxLength: 500
      format: password
    Timestamp:
      type: string
      format: date-time
    CompatibleEnvironmentTemplate:
      type: object
      required:
      - majorVersion
      - templateName
      properties:
        majorVersion:
          allOf:
          - $ref: '#/components/schemas/TemplateVersionPart'
          - description: The major version of the compatible environment template.
        templateName:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The compatible environment template name.
      description: Compatible environment template data.
    AccessDeniedException: {}
    ServiceTemplateVersionArn:
      type: string
    TemplateVersionStatus:
      type: string
      enum:
      - REGISTRATION_IN_PROGRESS
      - REGISTRATION_FAILED
      - DRAFT
      - PUBLISHED
    InternalServerException: {}
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/proton/
x-hasEquivalentPaths: true
