openapi: 3.2.0
info:
  version: 2020-07-20
  x-release: v4
  title: 'AWS Proton #X Amz Target=AwsProton20200720.ListServiceInstan…'
  description: This is the Proton Service API Reference.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: proton
  x-aws-signingName: proton
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/proton-2020-07-20.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://proton.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Proton multi-region endpoint
- url: https://proton.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Proton multi-region endpoint
- url: http://proton.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Proton endpoint for China (Beijing) and China (Ningxia)
- url: https://proton.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Proton endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AwsProton20200720.ListServiceInstances'
paths:
  /#X-Amz-Target=AwsProton20200720.ListServiceInstances:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListServiceInstances
      description: List service instances with summary data. This action lists service instances of all services in the Amazon Web Services account.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListServiceInstancesOutput'
        '480':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '481':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '482':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '483':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '484':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListServiceInstancesInput'
      parameters:
      - name: maxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AwsProton20200720.ListServiceInstances
      summary: Amazon Proton List Service Instances
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AwsProton20200720.ListServiceInstances'
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  schemas:
    ResourceName:
      type: string
      pattern: ^[0-9A-Za-z]+[0-9A-Za-z_\-]*$
      minLength: 1
      maxLength: 100
    ValidationException: {}
    ResourceNotFoundException: {}
    TemplateVersionPart:
      type: string
      pattern: ^(0|([1-9]{1}\d*))$
      minLength: 1
      maxLength: 20
    ListServiceInstancesOutput:
      type: object
      required:
      - serviceInstances
      properties:
        nextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: A token that indicates the location of the next service instance in the array of service instances, after the current requested list of service instances.
        serviceInstances:
          allOf:
          - $ref: '#/components/schemas/ServiceInstanceSummaryList'
          - description: An array of service instances with summary data.
    NextToken:
      type: string
      pattern: ^[A-Za-z0-9+=/]+$
    ListServiceInstancesFilterBy:
      type: string
      enum:
      - name
      - deploymentStatus
      - templateName
      - serviceName
      - deployedTemplateVersionStatus
      - environmentName
      - lastDeploymentAttemptedAtBefore
      - lastDeploymentAttemptedAtAfter
      - createdAtBefore
      - createdAtAfter
    ListServiceInstancesFilterValue:
      type: string
    ThrottlingException: {}
    StatusMessage:
      type: string
      format: password
    SortOrder:
      type: string
      enum:
      - ASCENDING
      - DESCENDING
    ServiceInstanceArn:
      type: string
    ListServiceInstancesFilterList:
      type: array
      items:
        $ref: '#/components/schemas/ListServiceInstancesFilter'
    ListServiceInstancesInput:
      type: object
      title: ListServiceInstancesInput
      properties:
        filters:
          allOf:
          - $ref: '#/components/schemas/ListServiceInstancesFilterList'
          - description: An array of filtering criteria that scope down the result list. By default, all service instances in the Amazon Web Services account are returned.
        maxResults:
          allOf:
          - $ref: '#/components/schemas/MaxPageResults'
          - description: The maximum number of service instances to list.
        nextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: A token that indicates the location of the next service in the array of service instances, after the list of service instances that was previously requested.
        serviceName:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The name of the service that the service instance belongs to.
        sortBy:
          allOf:
          - $ref: '#/components/schemas/ListServiceInstancesSortBy'
          - description: '<p>The field that the result list is sorted by.</p> <p>When you choose to sort by <code>serviceName</code>, service instances within each service are sorted by service instance name.</p> <p>Default: <code>serviceName</code> </p>'
        sortOrder:
          allOf:
          - $ref: '#/components/schemas/SortOrder'
          - description: '<p>Result list sort order.</p> <p>Default: <code>ASCENDING</code> </p>'
    Timestamp:
      type: string
      format: date-time
    DeploymentStatus:
      type: string
      enum:
      - IN_PROGRESS
      - FAILED
      - SUCCEEDED
      - DELETE_IN_PROGRESS
      - DELETE_FAILED
      - DELETE_COMPLETE
      - CANCELLING
      - CANCELLED
    MaxPageResults:
      type: integer
      minimum: 1
      maximum: 100
    ServiceInstanceSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/ServiceInstanceSummary'
    ListServiceInstancesSortBy:
      type: string
      enum:
      - name
      - deploymentStatus
      - templateName
      - serviceName
      - environmentName
      - lastDeploymentAttemptedAt
      - createdAt
    ServiceInstanceSummary:
      type: object
      required:
      - arn
      - createdAt
      - deploymentStatus
      - environmentName
      - lastDeploymentAttemptedAt
      - lastDeploymentSucceededAt
      - name
      - serviceName
      - templateMajorVersion
      - templateMinorVersion
      - templateName
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/ServiceInstanceArn'
          - description: The Amazon Resource Name (ARN) of the service instance.
        createdAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time when the service instance was created.
        deploymentStatus:
          allOf:
          - $ref: '#/components/schemas/DeploymentStatus'
          - description: The service instance deployment status.
        deploymentStatusMessage:
          allOf:
          - $ref: '#/components/schemas/StatusMessage'
          - description: A service instance deployment status message.
        environmentName:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The name of the environment that the service instance was deployed into.
        lastDeploymentAttemptedAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time when a deployment of the service was last attempted.
        lastDeploymentSucceededAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time when the service was last deployed successfully.
        name:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The name of the service instance.
        serviceName:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The name of the service that the service instance belongs to.
        templateMajorVersion:
          allOf:
          - $ref: '#/components/schemas/TemplateVersionPart'
          - description: The service instance template major version.
        templateMinorVersion:
          allOf:
          - $ref: '#/components/schemas/TemplateVersionPart'
          - description: The service instance template minor version.
        templateName:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The name of the service template.
      description: Summary data of an Proton service instance resource.
    ListServiceInstancesFilter:
      type: object
      properties:
        key:
          allOf:
          - $ref: '#/components/schemas/ListServiceInstancesFilterBy'
          - description: The name of a filtering criterion.
        value:
          allOf:
          - $ref: '#/components/schemas/ListServiceInstancesFilterValue'
          - description: <p>A value to filter by.</p> <p>With the date/time keys (<code>*At{Before,After}</code>), the value is a valid <a href="https://datatracker.ietf.org/doc/html/rfc3339.html">RFC 3339</a> string with no UTC offset and with an optional fractional precision (for example, <code>1985-04-12T23:20:50.52Z</code>).</p>
      description: A filtering criterion to scope down the result list of the <a>ListServiceInstances</a> action.
    AccessDeniedException: {}
    InternalServerException: {}
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/proton/
x-hasEquivalentPaths: true
