openapi: 3.2.0
info:
  version: 2020-07-20
  x-release: v4
  title: 'AWS Proton #X Amz Target=AwsProton20200720.ListEnvironmentTe…'
  description: This is the Proton Service API Reference.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: proton
  x-aws-signingName: proton
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/proton-2020-07-20.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://proton.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Proton multi-region endpoint
- url: https://proton.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Proton multi-region endpoint
- url: http://proton.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Proton endpoint for China (Beijing) and China (Ningxia)
- url: https://proton.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Proton endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AwsProton20200720.ListEnvironmentTemplateVersions'
paths:
  /#X-Amz-Target=AwsProton20200720.ListEnvironmentTemplateVersions:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListEnvironmentTemplateVersions
      description: List major or minor versions of an environment template with detail data.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListEnvironmentTemplateVersionsOutput'
        '480':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '481':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '482':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '483':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '484':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListEnvironmentTemplateVersionsInput'
      parameters:
      - name: maxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AwsProton20200720.ListEnvironmentTemplateVersions
      summary: Amazon Proton List Environment Template Versions
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AwsProton20200720.ListEnvironmentTemplateVersions'
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  schemas:
    ResourceName:
      type: string
      pattern: ^[0-9A-Za-z]+[0-9A-Za-z_\-]*$
      minLength: 1
      maxLength: 100
    ValidationException: {}
    ResourceNotFoundException: {}
    TemplateVersionPart:
      type: string
      pattern: ^(0|([1-9]{1}\d*))$
      minLength: 1
      maxLength: 20
    EnvironmentTemplateVersionArn:
      type: string
    ListEnvironmentTemplateVersionsInput:
      type: object
      required:
      - templateName
      title: ListEnvironmentTemplateVersionsInput
      properties:
        majorVersion:
          allOf:
          - $ref: '#/components/schemas/TemplateVersionPart'
          - description: <p>To view a list of minor of versions under a major version of an environment template, include <code>major Version</code>.</p> <p>To view a list of major versions of an environment template, <i>exclude</i> <code>major Version</code>.</p>
        maxResults:
          allOf:
          - $ref: '#/components/schemas/MaxPageResults'
          - description: The maximum number of major or minor versions of an environment template to list.
        nextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: A token that indicates the location of the next major or minor version in the array of major or minor versions of an environment template, after the list of major or minor versions that was previously requested.
        templateName:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The name of the environment template.
    NextToken:
      type: string
      pattern: ^[A-Za-z0-9+=/]+$
    ThrottlingException: {}
    StatusMessage:
      type: string
      format: password
    EnvironmentTemplateVersionSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/EnvironmentTemplateVersionSummary'
    Description:
      type: string
      minLength: 0
      maxLength: 500
      format: password
    Timestamp:
      type: string
      format: date-time
    MaxPageResults:
      type: integer
      minimum: 1
      maximum: 100
    ListEnvironmentTemplateVersionsOutput:
      type: object
      required:
      - templateVersions
      properties:
        nextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: A token that indicates the location of the next major or minor version in the array of major or minor versions of an environment template, after the list of major or minor versions that was previously requested.
        templateVersions:
          allOf:
          - $ref: '#/components/schemas/EnvironmentTemplateVersionSummaryList'
          - description: An array of major or minor versions of an environment template detail data.
    EnvironmentTemplateVersionSummary:
      type: object
      required:
      - arn
      - createdAt
      - lastModifiedAt
      - majorVersion
      - minorVersion
      - status
      - templateName
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/EnvironmentTemplateVersionArn'
          - description: The Amazon Resource Name (ARN) of the version of an environment template.
        createdAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time when the version of an environment template was created.
        description:
          allOf:
          - $ref: '#/components/schemas/Description'
          - description: A description of the version of an environment template.
        lastModifiedAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time when the version of an environment template was last modified.
        majorVersion:
          allOf:
          - $ref: '#/components/schemas/TemplateVersionPart'
          - description: The latest major version that's associated with the version of an environment template.
        minorVersion:
          allOf:
          - $ref: '#/components/schemas/TemplateVersionPart'
          - description: The version of an environment template.
        recommendedMinorVersion:
          allOf:
          - $ref: '#/components/schemas/TemplateVersionPart'
          - description: The recommended minor version of the environment template.
        status:
          allOf:
          - $ref: '#/components/schemas/TemplateVersionStatus'
          - description: The status of the version of an environment template.
        statusMessage:
          allOf:
          - $ref: '#/components/schemas/StatusMessage'
          - description: The status message of the version of an environment template.
        templateName:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The name of the environment template.
      description: A summary of the version of an environment template detail data.
    AccessDeniedException: {}
    TemplateVersionStatus:
      type: string
      enum:
      - REGISTRATION_IN_PROGRESS
      - REGISTRATION_FAILED
      - DRAFT
      - PUBLISHED
    InternalServerException: {}
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/proton/
x-hasEquivalentPaths: true
