openapi: 3.2.0
info:
  version: 2020-07-20
  x-release: v4
  title: 'AWS Proton #X Amz Target=AwsProton20200720.DeleteEnvironment…'
  description: This is the Proton Service API Reference.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: proton
  x-aws-signingName: proton
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/proton-2020-07-20.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://proton.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Proton multi-region endpoint
- url: https://proton.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Proton multi-region endpoint
- url: http://proton.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Proton endpoint for China (Beijing) and China (Ningxia)
- url: https://proton.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Proton endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AwsProton20200720.DeleteEnvironmentTemplate'
paths:
  /#X-Amz-Target=AwsProton20200720.DeleteEnvironmentTemplate:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DeleteEnvironmentTemplate
      description: If no other major or minor versions of an environment template exist, delete the environment template.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteEnvironmentTemplateOutput'
        '480':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '481':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '482':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '483':
          description: ConflictException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
        '484':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '485':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteEnvironmentTemplateInput'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AwsProton20200720.DeleteEnvironmentTemplate
      summary: Amazon Proton Delete Environment Template
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AwsProton20200720.DeleteEnvironmentTemplate'
components:
  schemas:
    FullTemplateVersionNumber:
      type: string
      pattern: ^(0|([1-9]{1}\d*)).(0|([1-9]{1}\d*))$
      minLength: 1
      maxLength: 10
    ResourceName:
      type: string
      pattern: ^[0-9A-Za-z]+[0-9A-Za-z_\-]*$
      minLength: 1
      maxLength: 100
    ValidationException: {}
    EnvironmentTemplateArn:
      type: string
    ResourceNotFoundException: {}
    Arn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-us-gov):[a-zA-Z0-9-]+:[a-zA-Z0-9-]*:\d{12}:([\w+=,.@-]+[/:])*[\w+=,.@-]+$
      minLength: 1
      maxLength: 200
    ConflictException: {}
    ThrottlingException: {}
    DeleteEnvironmentTemplateInput:
      type: object
      required:
      - name
      title: DeleteEnvironmentTemplateInput
      properties:
        name:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The name of the environment template to delete.
    DisplayName:
      type: string
      minLength: 1
      maxLength: 100
      format: password
    Description:
      type: string
      minLength: 0
      maxLength: 500
      format: password
    Timestamp:
      type: string
      format: date-time
    Provisioning:
      type: string
      enum:
      - CUSTOMER_MANAGED
    DeleteEnvironmentTemplateOutput:
      type: object
      properties:
        environmentTemplate:
          allOf:
          - $ref: '#/components/schemas/EnvironmentTemplate'
          - description: The detailed data of the environment template being deleted.
    EnvironmentTemplate:
      type: object
      required:
      - arn
      - createdAt
      - lastModifiedAt
      - name
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/EnvironmentTemplateArn'
          - description: The Amazon Resource Name (ARN) of the environment template.
        createdAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time when the environment template was created.
        description:
          allOf:
          - $ref: '#/components/schemas/Description'
          - description: A description of the environment template.
        displayName:
          allOf:
          - $ref: '#/components/schemas/DisplayName'
          - description: The name of the environment template as displayed in the developer interface.
        encryptionKey:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The customer provided encryption key for the environment template.
        lastModifiedAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time when the environment template was last modified.
        name:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The name of the environment template.
        provisioning:
          allOf:
          - $ref: '#/components/schemas/Provisioning'
          - description: When included, indicates that the environment template is for customer provisioned and managed infrastructure.
        recommendedVersion:
          allOf:
          - $ref: '#/components/schemas/FullTemplateVersionNumber'
          - description: The ID of the recommended version of the environment template.
      description: The environment template data.
    AccessDeniedException: {}
    InternalServerException: {}
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/proton/
x-hasEquivalentPaths: true
