openapi: 3.2.0
info:
  version: 2020-07-20
  x-release: v4
  title: 'AWS Proton #X Amz Target=AwsProton20200720.ListRepositorySyn…'
  description: This is the Proton Service API Reference.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: proton
  x-aws-signingName: proton
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/proton-2020-07-20.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://proton.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Proton multi-region endpoint
- url: https://proton.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Proton multi-region endpoint
- url: http://proton.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Proton endpoint for China (Beijing) and China (Ningxia)
- url: https://proton.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Proton endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AwsProton20200720.ListRepositorySyncDefinitions'
paths:
  /#X-Amz-Target=AwsProton20200720.ListRepositorySyncDefinitions:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListRepositorySyncDefinitions
      description: List repository sync definitions with detail data.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListRepositorySyncDefinitionsOutput'
        '480':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '481':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '482':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '483':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListRepositorySyncDefinitionsInput'
      parameters:
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AwsProton20200720.ListRepositorySyncDefinitions
      summary: Amazon Proton List Repository Sync Definitions
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AwsProton20200720.ListRepositorySyncDefinitions'
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  schemas:
    ValidationException: {}
    RepositoryName:
      type: string
      pattern: '[A-Za-z0-9_.-].*/[A-Za-z0-9_.-].*'
      minLength: 1
      maxLength: 100
    String:
      type: string
    RepositoryProvider:
      type: string
      enum:
      - GITHUB
      - GITHUB_ENTERPRISE
      - BITBUCKET
    RepositorySyncDefinitionList:
      type: array
      items:
        $ref: '#/components/schemas/RepositorySyncDefinition'
    ThrottlingException: {}
    ListRepositorySyncDefinitionsOutput:
      type: object
      required:
      - syncDefinitions
      properties:
        nextToken:
          allOf:
          - $ref: '#/components/schemas/EmptyNextToken'
          - description: A token that indicates the location of the next repository sync definition in the array of repository sync definitions, after the current requested list of repository sync definitions.
        syncDefinitions:
          allOf:
          - $ref: '#/components/schemas/RepositorySyncDefinitionList'
          - description: An array of repository sync definitions.
    EmptyNextToken:
      type: string
      minLength: 0
      maxLength: 0
    SyncType:
      type: string
      enum:
      - TEMPLATE_SYNC
      - SERVICE_SYNC
    ListRepositorySyncDefinitionsInput:
      type: object
      required:
      - repositoryName
      - repositoryProvider
      - syncType
      title: ListRepositorySyncDefinitionsInput
      properties:
        nextToken:
          allOf:
          - $ref: '#/components/schemas/EmptyNextToken'
          - description: A token that indicates the location of the next repository sync definition in the array of repository sync definitions, after the list of repository sync definitions previously requested.
        repositoryName:
          allOf:
          - $ref: '#/components/schemas/RepositoryName'
          - description: The repository name.
        repositoryProvider:
          allOf:
          - $ref: '#/components/schemas/RepositoryProvider'
          - description: The repository provider.
        syncType:
          allOf:
          - $ref: '#/components/schemas/SyncType'
          - description: The sync type. The only supported value is <code>TEMPLATE_SYNC</code>.
    AccessDeniedException: {}
    RepositorySyncDefinition:
      type: object
      required:
      - branch
      - directory
      - parent
      - target
      properties:
        branch:
          allOf:
          - $ref: '#/components/schemas/GitBranchName'
          - description: The repository branch.
        directory:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The directory in the repository.
        parent:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The resource that is synced from.
        target:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The resource that is synced to.
      description: A repository sync definition.
    GitBranchName:
      type: string
      minLength: 1
      maxLength: 200
    InternalServerException: {}
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/proton/
x-hasEquivalentPaths: true
